language: cpp
os: osx
osx_image: xcode7.3
install:
  - brew update
  - brew install --only-dependencies --build-bottle file://${TRAVIS_BUILD_DIR}/qt.rb
script:
  - travis_wait 90 brew install --build-bottle file://${TRAVIS_BUILD_DIR}/qt.rb
  - brew bottle qt