language: cpp
os: osx
osx_image: 
  - xcode6.4
  - xcode7.3
  - xcode8.3
install:
  - brew update
  - brew install --only-dependencies --build-bottle file://${TRAVIS_BUILD_DIR}/qt@4.rb
script:
  - travis_wait 90 brew install --build-bottle file://${TRAVIS_BUILD_DIR}/qt@4.rb
  - brew bottle qt@4
deploy:
  provider: bintray
  file: bintray.json
  user: "cartr"
  key:
    secure: KfOXmMCCus15Nt/FNkO0K2c40mwL3mTUd8bfpBGlAvaH14vEbX9lbEkd0MniTk2kbeiiXwS0S9T2TUzfJ8l1/RVfD2jzwi5hZAEjPLHH+wvb8Fivccmq/ehSvyVQduA8gxL8Gd04r+pxHuz6n5QtV/KjdJJTULROmx70uFSVrrZypzqSyCCDHMhqvMAfy7jhBbNg7CjwHNHETeeNdxz6ZjUllqOPW030j6f0ud7bWon5LPsK0o3GDEXY7morr7Cr5hoGpk7fno/m9bS7RYTWAsl6B7d5OkoSpa3VraRDpDiBb99WXU9MAznQtcBusTPmgj3cmiXfOWNH0Wn2vNR8mnZ0td57lZhxCuJx9Mn3LFBBbUrGNzmb0xkfpEJIOMl6YBAtSKXT/6jIX66CO+L6rMD5RVlz1PlMSqvSU8XZO/EnCG6nMmgDSiMl9MiEadBAtZ4SW2p2MrgXSuymnbKALX84Kn2SC6lwZ/h3xFIr73IOLxk3w8+SEbpdWwDyP92wTdxSwUX/yZSVd51i2uXQwh8tGgRfYcegLfdn5jFCwguYFKRTcmhbRP6L/l7za/lJxEL1KwCsTzpMcVzqaoXNORtzXIcdFI7QTWiUeqof447k83/zEpcfqjEcviQP5XPSBFcqZ9QKoJoNInQ6ixkM32CYK7Io7Vpl9lXcQqHzaMI=
    